config/routes.rb
Rails.application.routes.draw do
  
  resources :locations
  resources :searches
  devise_for :users
  resources :cases
  root 'welcome#index'
end

app/models/case.rb
class Case < ActiveRecord::Base
end

app/models/location.rb
class Location < ActiveRecord::Base

	def self.search(search)
		if search
			where("city LIKE ?", "%#{search}%")
		else
			all
		end
	end
end

app/models/search.rb
class Search < ActiveRecord::Base

	def search_locations
		locations = Location.all

		locations = locations.where("city LIKE ?", city) if city.present?
		locations = locations.where("governorate LIKE ?", governorate) if governorate.present?
		locations = locations.where("country LIKE ?", country) if country.present?

		return locations
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_governorates
  
  def get_api_key
    if user_signed_in?
      @api_key = current_user.api_key
    else
      @api_key = ""
    end
  end

  def get_governorates
  	@allgovs = Location.uniq.pluck(:governorate)
  end

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :edit, :update, :destroy]

  # GET /cases
  # GET /cases.json
  def index
    @cases = Case.all
  end

  # GET /cases/1
  # GET /cases/1.json
  def show
  end

  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  # POST /cases.json
  def create
    @case = Case.new(case_params)

    respond_to do |format|
      if @case.save
        format.html { redirect_to @case, notice: 'Case was successfully created.' }
        format.json { render :show, status: :created, location: @case }
      else
        format.html { render :new }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cases/1
  # PATCH/PUT /cases/1.json
  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to @case, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cases/1
  # DELETE /cases/1.json
  def destroy
    @case.destroy
    respond_to do |format|
      format.html { redirect_to cases_url, notice: 'Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case
      @case = Case.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_params
      params.require(:case).permit(:case_number, :country, :date_fled)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @location = Location.search(params[:search]).first
  end

  def search
    if params[:search]
      @location = Location.search(params[:search]).first
    else
      @location = Location.all.first
    end 
    render 'locations/search'
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :governorate, :country, :description)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	def new
		@search = Search.new
		@governorates = Location.uniq.pluck(:governorate)
	end

	def create
		@search = Search.create(search_params)
		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
	end

	private
	def search_params
		params.require(:search).permit(:keywords, :city, :governorate, :country)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :get_api_key
  def index
  	if user_signed_in?
  		@api_key = current_user.api_key
  	else
  		@api_key = ""
  	end
  end

  def get_api_key
    if user_signed_in?
      @api_key = current_user.api_key
    else
      @api_key = ""
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cases/_form.html.erb
<%= form_for(@case) do |f| %>
  <% if @case.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@case.errors.count, "error") %> prohibited this case from being saved:</h2>

      <ul>
      <% @case.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :case_number %><br>
    <%= f.text_field :case_number %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :date_fled %><br>
    <%= f.date_select :date_fled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cases/edit.html.erb
<h1>Editing Case</h1>

<%= render 'form' %>

<%= link_to 'Show', @case %> |
<%= link_to 'Back', cases_path %>

app/views/cases/index.html.erb
<h1>Listing Cases</h1>

<table>
  <thead>
    <tr>
      <th>Case number</th>
      <th>Country</th>
      <th>Date fled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cases.each do |c| %>
      <tr>
        <td><%= c.case_number %></td>
        <td><%= c.country %></td>
        <td><%= c.date_fled %></td>
        <td><%= link_to 'Show', c %></td>
        <td><%= link_to 'Edit', edit_case_path(c) %></td>
        <td><%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Case', new_case_path %>

app/views/cases/new.html.erb
<h1>New Case</h1>

<%= render 'form' %>

<%= link_to 'Back', cases_path %>

app/views/cases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Case number:</strong>
  <%= @case.case_number %>
</p>

<p>
  <strong>Country:</strong>
  <%= @case.country %>
</p>

<p>
  <strong>Date fled:</strong>
  <%= @case.date_fled %>
</p>

<%= link_to 'Edit', edit_case_path(@case) %> |
<%= link_to 'Back', cases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Countryconditions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link type="text/css" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>


</head>
<body>
<%= render 'partials/user' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="main container" class="container">
	<div class = "row">
		<div class="col-sm-2">
		<%= render 'partials/sidebar' %>
		</div>
		<div id="content" class= "col-sm-7">
				<%= yield %>
		</div>
	</div>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :governorate %><br>
    <%= f.text_field :governorate %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/_location.html.erb
<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Governorate:</strong>
  <%= @location.governorate %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>City</th>
      <th>Governorate</th>
      <th>Country</th>
      <th>Description</th>
      <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.city %></td>
        <td><%= location.governorate %></td>
        <td><%= location.country %></td>
        <td><%= location.description %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Advanced Search",  new_search_path %>
<%= form_tag locations_path, :method => 'get' do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<% if !@location.nil? %>
  <%= render @location %>
<% else %>
  <p> There are no locations found!</p>
<% end %>
<br>


<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/search.html.erb
<%= @location %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Governorate:</strong>
  <%= @location.governorate %>
</p>

<p>
  <strong>Country:</strong>
  <%= @location.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/partials/_sidebar.html.erb
<div class="list-group">
	<%= image_tag('ROASTlogo.jpg', :class => "img-responsive", :alt => "ROAST - Online") %>
	<%= link_to "Look Up Location", new_search_path, :class => "list-group-item" %>
	<% @allgovs.each do |g| %>
		<%= link_to g, "", :class => "list-group-item" %>
	<% end %>
</div>

app/views/partials/_user.html.erb
  <!--div class="btn-group open">
  <a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
  <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
    <span class="fa fa-caret-down"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#"><i class="fa fa-pencil fa-fw"></i> Edit</a></li>
    <li><a href="#"><i class="fa fa-trash-o fa-fw"></i> Delete</a></li>
    <li><a href="#"><i class="fa fa-ban fa-fw"></i> Ban</a></li>
    <li class="divider"></li>
    <li><a href="#"><i class="i"></i> Make admin</a></li>
  </ul>
</div-->
<nav class="navbar navbar-fixed-top navbar-default ">
  <div class="container">
    <ul class="nav navbar-nav navbar-left">
    <%= link_to "Refugee Affairs Division - ROAST Online", root_path, :class => 'navbar-brand' %> 
      <% if user_signed_in? %>

        <%=link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'btn btn-default navbar-btn' %>

      <% else %>

        <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-default navbar-btn' %>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-default navbar-btn'%>
    </ul>
    <% end %>
  </div>

</nav>
<div class='clearfix'></div>

app/views/searches/new.html.erb
<h1> Custom Search <br/> <small> Let <em> The ROAST </em> help you find where your applicant is from... </small></h1>

<br />
<%= form_for @search, html:{class: "form-horizontal"} do |s| %>
	<div class="form-group row" id="locationField">
		<div class="col-sm-9">

			<input id="autocomplete" type="text" placeholder="Enter your applicant's location" onfocus="geolocate()" class="form-control"> 
		</div>
	</div>
	<div class="form-group row">
		<%= s.label :keyword, :class => 'col-sm-3 control-label', :for=>'keywords' %><br />
		<div class="col-sm-6">
		<%= s.text_field :keywords, :id => 'keywords', :class => 'form-control' %>
		</div>
	</div>

	<div class="form-group row">
		<%= s.label :governorate, :class => 'col-sm-3 control-label', :for => 'administrative_area_level_1' %> 
		<div class="col-sm-6">
		<%= s.select :governorate,  options_for_select(@governorates), {:include_blank => true}, {:class => 'form-control', :id => 'administrative_area_level_1'} %>
		</div>
	</div>


	<div class="form-group row">
		<%= s.label :city, :class => 'col-sm-3 control-label', :for => 'locality' %>
		<div class="col-sm-6">
			<%= s.text_field :city, :id => 'locality', :class => "form-control" %>
		</div>
	</div>

	<div class="form-group row">
		<%= s.label :country, :class => 'col-sm-3 control-label'  %>
		<div class="col-sm-6">
			<%= s.text_field :country, :id => 'country', :class => "form-control" %>
		</div>
	</div>

	<div class="actions"><%=s.submit "Search", class: "btn btn-default" %>
	</div>

<% end %>

<%- link_to 'Locations', locations_path %>

  <script src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key %>&libraries=places&callback=initAutocomplete"
      async defer>
  </script>

app/views/searches/show.html.erb
<h1> Search Results </h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_locations.empty? %>
<p> No Records Found </p>

<% else %>

	<% @search.search_locations.each do |l| %>
		<br>

		<div>
			<h1><%= l.city %>
			</h1>
			<p>Governorate: <%= l.governorate %> </p>
			<p>Country: <%= l.country %></p>
			<p>Description: <%= l.description %> 
			</p>
		</div>
	<% end %>
<% end %>

app/views/welcome/index.html.erb
<h1> Welcome to the <em> Future </em> of Country Condition Resources </h1>

<p>
To get started begin navigating on the side - or check out one of the most recent additions below...
</p>


<%= link_to "Custom Area Search - To Find Your Applicant's Location in Syria...Every Time", new_search_path, :class => "btn btn-success" %>

<!--
  <% if user_signed_in? %>

     <form class="form-horizontal">
      <div class="form-group row" id="locationField">
        <div class="col-sm-9">
          <input  id="autocomplete" type="text" placeholder="Enter your address" onfocus="geolocate()" class="form-control" >
        </div> 
      </div>
      <div class= " form-group row">
        <label for="locality" class="col-sm-3 control-label">City</label>
        <div class="col-sm-6">
          <input id="locality" type="locality" class="form-control"  placeholder="">
        </div>
      </div>
      <div class= "form-group row">
        <label for="administrative_area_level_1" class="col-sm-3 control-label">Governorate</label>
        <div class="col-sm-6">
          <input id="administrative_area_level_1" type="administrative_area_level_1" class="form-control"  placeholder="">
        </div>
      </div>
      <div class= "form-group row">
        <label for="administrative_area_level_2" class="col-sm-3 control-label">District</label>
        <div class="col-sm-6">
          <input id="administrative_area_level_2" type="administrative_area_level_2" class="form-control"  placeholder=""> 
        </div>
      </div>
      <div class= "form-group row">
        <label for="neighborhood" class="col-sm-3 control-label">Neighborhood (if applicable)</label>
        <div class="col-sm-6">
          <input id="neighborhood" type="neighborhood" class="form-control" placeholder="">
        </div>
      </div>
      <div class= "form-group row">
        <label for="country" class="col-sm-3 control-label">Country</label>
        <div class="col-sm-6">
          <input id="country". type="country" class="form-control"  placeholder="">
        </div>
      </div>
    </form>
  </div>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= @api_key %>&libraries=places&callback=initAutocomplete"
      async defer>
  </script>
<% end %> -->